GET HTTP://localhost:3000/api/getQuestion-Queries

###


GET HTTP://localhost:3000/api/getQuestion-Queries/600a59b32c8fd823885cec0b


###

DELETE HTTP://localhost:3000/api/deleteQuestion-Queries/600a599d2c8fd823885cec08

###

PATCH HTTP://localhost:3000/api/updateQuestion-Queries/600a59b32c8fd823885cec0b
Content-Type: application/json

{
    "description" : "not your mom"
}

###
POST HTTP://localhost:3000/api/sendQuestion-Queries
Content-Type: application/json

{
    "title" : "Disney",
    "description" : "questions on different disney characters",
    "questions" :
    [   {
            "question" : "When was cars 1 released?",
            "answers" : {
                "Q1": "1992",
                "Q2": "2012",
                "Q3": "2005",
                "Q4": "2015"
                },
            "correct_answer" : "Q3"
        },
        {
            "question" : "Which princess has long hair?",
            "answers" : {
                "Q1": "Repunzal",
                "Q2": "Cindereala",
                "Q3": "That dude from down the street",
                "Q4": "that frog chick"
                },
            "correct_answer" : "Q4"
        }
    ]
}

###

POST http://localhost:3000/api/host
Content-Type: application/json

###

GET http://localhost:3000/api/play/GIRT9D5T

###

POST http://localhost:3000/api/play/GIRT9D5T
Content-Type: application/json

{
    "name" : "retard"
}