GET HTTP://localhost:3000/api/getQuestion-Queries

###


GET HTTP://localhost:3000/api/getQuestion-Queries/600a59b32c8fd823885cec0b


###

DELETE HTTP://localhost:3000/api/deleteQuestion-Queries/600a599d2c8fd823885cec08

###

PATCH HTTP://localhost:3000/api/updateQuestion-Queries/600a59b32c8fd823885cec0b
Content-Type: application/json

{
    "description" : "not your mom"
}

###
POST HTTP://localhost:3000/api/sendQuestion-Queries
Content-Type: application/json

{
    "title" : "Things Bryan says",
    "description" : "What would bryan say?",
    "category" : "bryan",
    "questions" :
    [   {
            "question" : "what is bryans favorite word?",
            "answers" : {
                "Q1": "penis",
                "Q2": "poop",
                "Q3": "pee pee",
                "Q4": "your mom"
                },
            "correct_answer" : "Q4"
        },
        {
            "question" : "How many times has bryan said he'd stop talking to julie?",
            "answers" : {
                "Q1": "too many fucking times",
                "Q2": "I'm horny",
                "Q3": "I haven't had sex in over 2 months man.",
                "Q4": "Who's julie?"
                },
            "correct_answer" : "Q2"
        },
        {
            "question" : "Whos bryans best friend",
            "answers" : {
                "Q1": "Pussy",
                "Q2": "Pussy",
                "Q3": "Pussy",
                "Q4": "your mom"
                },
            "correct_answer" : "Q4"
        },
        {
            "question" : "How many times has bryan said he'd stop talking to julie?",
            "answers" : {
                "Q1": "too many fucking times",
                "Q2": "I'm horny",
                "Q3": "I haven't had sex in over 2 months man.",
                "Q4": "Who's julie?"
                },
            "correct_answer" : "Q2"
        },
        {
            "question" : "How many times has bryan said he'd stop talking to julie?",
            "answers" : {
                "Q1": "too many fucking times",
                "Q2": "I'm horny",
                "Q3": "I haven't had sex in over 2 months man.",
                "Q4": "Who's julie?"
                },
            "correct_answer" : "Q2"
        },
        {
            "question" : "How many times has bryan said he'd stop talking to julie?",
            "answers" : {
                "Q1": "too many fucking times",
                "Q2": "I'm horny",
                "Q3": "I haven't had sex in over 2 months man.",
                "Q4": "Who's julie?"
                },
            "correct_answer" : "Q2"
        },
        {
            "question" : "How many times has bryan said he'd stop talking to julie?",
            "answers" : {
                "Q1": "too many fucking times",
                "Q2": "I'm horny",
                "Q3": "I haven't had sex in over 2 months man.",
                "Q4": "Who's julie?"
                },
            "correct_answer" : "Q2"
        }
    ]
}

###

POST http://localhost:3000/api/create-room
Content-Type: application/json

###

GET http://localhost:3000/api/play/GIRT9D5T

###

POST http://localhost:3000/api/play/GIRT9D5T
Content-Type: application/json

{
    "name" : "retard"
}